server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: fabrick_interview_task1
  main:
    web-application-type: servlet
  cache:
    type: caffeine
    caffeine:
      maximum-size: 1000
      expire-after-write: 86400000 # 24 hours in milliseconds

application:
  nasa:
    api:
      base-url: https://api.nasa.gov/neo/rest/v1/neo
      api-key: ${NASA_API_KEY:DEMO_KEY} # for production use a secret manager

logging:
  level:
    com.example.fabrick_task1: INFO
    org.springframework.web.client: INFO
    org.springframework.cache: TRACE
    com.github.benmanes.caffeine: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %X{correlationId:-N/A} | %logger{1.} | %msg%n"