server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: fabrick_interview_task1
  main:
    web-application-type: servlet
  cache:
    type: caffeine
    caffeine:
      maximum-size: 1000
      expire-after-write: 86400000 # 24 hours in milliseconds

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{1.} | %msg%n"